language: python

env:
  global:
    - TWINE_USERNAME=dwtools
    - secure: "WoAVejcu1/5gTrv+NcVKc98mJrdApZn15KOBH0gbDhsn1dXPduGprVkuGaMNFuTDKukdPRCJ24DOLk8Du/u2vE9trMJ+aDhE1FN+jRE4Ott6uJhS60JECmr806466RgHe65e+42RwpLY3zAtIB2pgkCji4j7y0uWXMM4P3nq4RUb0W/K/z0n87bvKzZs87KSScLGPa3gc9YdK063KMmfGrDPye6hmzlxnT4zCEvk+aghhu8QOru801NQptX2HyAVBskWMBN6du4uCXAMY4bcKSvBqXRVc92O4s6WDvUySdKRBintAY0FT1QldT6ez+jSDoVAPnx3WhHzekEU82IDRPaKFFhbk9SAIEhHx2/sdAS+FjVy63hGNmQ+KuPpLycUhjFOxMg0C0VCNv8FHmg1ItL4asUmREHpsf6dnhJfwz6j2j18bXHbF6qxmJE0oHyQbCQQQ7blf1pn5pzl+jiLxoC9enxR2SEYgbubfI8hjB49ZOh2IBMZR1+Px1LFYHJWQnbNxn45fGCw8HKbA8L+qkuuUhVqIP2x7BVgd4hOnWaBqtXUbxqrmW1McKzsoKS/IvajWUvkANtZuVrLFffgCKWAf/FrSAo1fbyE5Jy2d6dilJ/O636XUAdJgNk8mlj5Dxfo9K1m5YsulTyZh3XiFTeH4/4UYrZDBexi2B0URQI="

matrix:
  include:
    - language: c
      script: ./ci/travis/cpp-coverage.sh
      deploy:
      env: C_COMPILER=gcc CXX_COMPILER=g++
    - language: c
      script: ./ci/travis/cpp-coverage.sh
      deploy:
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
         - C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8
    - language: c
      script: ./ci/travis/cpp-coverage.sh
      deploy:
      env: C_COMPILER=clang CXX_COMPILER=clang++
    - language: c
      os: osx
      script: ./ci/travis/osx-cpp-coverage.sh
      deploy:
      env: C_COMPILER=gcc CXX_COMPILER=g++
    - language: c
      os: osx
      script: ./ci/travis/osx-cpp-coverage.sh
      deploy:
      env: C_COMPILER=clang CXX_COMPILER=clang++
    - language: python
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - language: python
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
    - os: osx
      language: generic
      before_install:
        - brew update
        - virtualenv env -p python2
        - source env/bin/activate
      script:
        - ./ci/travis/osx-debug-wheel.sh
      deploy:
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      script:
        - ./ci/travis/osx-debug-wheel.sh
      deploy:
    - os: osx
      language: generic
      before_install:
        - brew update
        - virtualenv env -p python2
        - source env/bin/activate
      script:
        - ./ci/travis/osx-build-wheel.sh
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      script:
        - ./ci/travis/osx-build-wheel.sh
      after_success:
        - pip install twine
        - python setup.py sdist
        - echo after_success
        - pwd
        - ls
      deploy:
        provider: script
        script:
            - echo deploy
            - pwd
            - ls
            - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD --skip-existing dist/*
            - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD --skip-existing wheelhouse/*
        skip_cleanup: true
        on:
          tags: true
    # - os: osx
    #   language: generic
    #   env: TOXENV=pynightly


script:
  - docker pull $DOCKER_IMAGE
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/ci/travis/linux-debug-wheels.sh
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/ci/travis/linux-build-wheels.sh
  - ls wheelhouse/

after_success:
  - pip install twine

deploy:
  provider: script
  script:
      - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD --skip-existing wheelhouse/*
  skip_cleanup: true
  on:
    tags: true
